name: Test Build Without Secrets

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-only:
    runs-on: [self-hosted,RUNNER37]

    steps:
      # 1) Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3) Check Node.js & NPM version
      - name: Check Node.js & NPM version
        shell: cmd
        run: |
          node --version
          npm --version

      # 4) Install dependencies
      - name: Install dependencies
        shell: cmd
        run: npm ci --prefer-offline --no-audit

      # 5) Build Angular
      - name: Build Angular
        shell: cmd
        run: npm run build -- --configuration production --aot --build-optimizer

      # 6) Verify build output
      - name: Verify build output
        shell: cmd
        run: |
          if exist dist\wms-frontend-new\browser (
            echo Build successful
          ) else (
            echo Build failed
            exit 1
          )

      # 7) Create deployment package
      - name: Create deployment package
        shell: cmd
        run: powershell -Command "Compress-Archive -Path 'dist\wms-frontend-new\browser\*' -DestinationPath 'deployment.zip' -Force"

      # 8) Show package info
      - name: Package information
        shell: cmd
        run: powershell -Command "Get-Item 'deployment.zip' | Format-List Name, Length, CreationTime"
