name: Test Build Without Secrets

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-only:
    runs-on: self-hosted

    steps:
      # 1) Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3) Check Node.js and npm version
      - name: Check Node.js & NPM version
        shell: pwsh
        run: |
          node --version
          npm --version

      # 4) Install dependencies
      - name: Install dependencies
        shell: pwsh
        run: npm ci --prefer-offline --no-audit

      # 5) Build Angular
      - name: Build Angular
        shell: pwsh
        run: npm run build -- --configuration production --aot --build-optimizer

      # 6) Verify build output
      - name: Verify build output
        shell: pwsh
        run: |
          if (Test-Path "dist/wms-frontend-new/browser") {
              Write-Output "Build successful"
          } else {
              Write-Error "Build failed - dist folder not found"
              exit 1
          }

      # 7) Create deployment package
      - name: Create deployment package
        shell: pwsh
        run: |
          Compress-Archive -Path "dist/wms-frontend-new/browser/*" -DestinationPath "deployment.zip" -Force

      # 8) Show package info
      - name: Package information
        shell: pwsh
        run: |
          $zip = Get-Item "deployment.zip"
          Write-Output "Package size: $($zip.Length) bytes"
          Write-Output "Package created at: $($zip.CreationTime)"
