# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: server_deploy

on:
  push:
      tags:
      - 'v*'  # จะ trigger เมื่อ push tag ที่ขึ้นต้นด้วย 'v' เช่น v1.0.0
  # เอา push branches และ pull_request ออก เพื่อไม่ให้ deploy ทุกครั้ง
  #npm version patch  # เพิ่ม patch version  # 1.0.0 -> 1.0.1
  # หรือ
  #npm version minor  # เพิ่ม minor version # 1.0.0 -> 1.1.0
  # หรือ
  #npm version major  # เพิ่ม major version # 1.0.0 -> 2.0.0
  #git push origin master --tags
  # git push --tags ส่ง tag ขึ้น remote ด้วย
  
  # เพิ่ม tag ด้วยคำสั่ง git tag v1.0.0 แล้ว push ขึ้น remote
  # git push origin v1.0.0

  # หรือใช้คำสั่ง
  # git push --tags

  workflow_dispatch:  # เพิ่มไว้เผื่อต้องการ manual trigger
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Read package.json version
        id: package_version
        shell: powershell
        run: |
          $packageJson = Get-Content -Raw -Path "package.json" | ConvertFrom-Json
          $version = $packageJson.version
          Write-Output "PACKAGE_VERSION=$version" >> $env:GITHUB_OUTPUT
          Write-Output "Package version: $version"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build -- --configuration production

      - name: Backup old IIS files with timestamp
        shell: powershell
        run: |
          $webRoot   = "C:\inetpub\wwwroot\WMS_Pro"
          $backupDir = "C:\inetpub\wwwroot\WMS_Pro_Backup"
          $timestamp = Get-Date -Format "yyyy-MM-dd-HHmm"
          $currentBackup = Join-Path $backupDir $timestamp

          Write-Output "Preparing backup..."
          if (-Not (Test-Path $backupDir)) {
            New-Item -ItemType Directory -Path $backupDir | Out-Null
            Write-Output "Backup root folder created: $backupDir"
          }

          if (Test-Path $webRoot) {
            New-Item -ItemType Directory -Path $currentBackup | Out-Null
            Copy-Item -Path (Join-Path $webRoot '*') -Destination $currentBackup -Recurse -Force
            Write-Output "Old web files copied to backup folder: $currentBackup"
          } else {
            Write-Output "Web root does not exist: $webRoot"
          }

      - name: Deploy new build to IIS (overwrite all except web.config)
        shell: powershell
        run: |
          $source = "dist\wms-frontend-new\browser\*"
          $destination = "C:\inetpub\wwwroot\WMS_Pro"
      
          Write-Output "Cleaning old files (except web.config)..."
      
          # ลบไฟล์เดิมทั้งหมดใน web root ยกเว้น web.config
          Get-ChildItem -Path $destination -Recurse -File | Where-Object { $_.Name -ne "web.config" } | Remove-Item -Force
      
          # ลบโฟลเดอร์เปล่าที่เหลือ
          Get-ChildItem -Path $destination -Recurse -Directory | Where-Object { $_.GetFileSystemInfos().Count -eq 0 } | Remove-Item -Force
      
          Write-Output "Deploying new build..."
          # คัดลอกไฟล์ build ใหม่ทั้งหมด (รวมโฟลเดอร์ย่อย) ไป web root
          Copy-Item -Path $source -Destination $destination -Recurse -Force
      
          Write-Output "New build deployed to $destination (web.config preserved)."


      - name: Restart IIS site
        shell: powershell
        run: |
          Import-Module WebAdministration
          Restart-WebAppPool -Name "WMS PRO"
          Restart-WebItem 'IIS:\Sites\WMS PRO'
          Write-Output "IIS site 'WMS PRO' restarted successfully."

